---
- name: install packages to use gpg with a smartcard
  become: yes
  package:
    name: "{{item}}"
    state: present
  with_items:
    - gnupg2 #for key crypto
    - scdaemon #smart card (yubikey) integration
    - pcscd #smart card handling (yubikey)
    - git #store sync backend
    - rng-tools #true random numbers from HW

- name: download gopass from github
  get_url:
    url: "{{ gopass_url }}"
    dest: "/tmp/{{ gopass_deb_name }}"
    mode: '0440'

- name: install gopass package
  become: yes
  apt:
    deb: "/tmp/{{ gopass_deb_name }}"
  